[package]
name = "tower-web"
version = "0.1.0"
authors = ["David Pedersen <david.pdrsn@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
bytes = "1.0"
futures-util = "0.3"
http = "0.2"
http-body = "0.4"
hyper = "0.14"
itertools = "0.10"
pin-project = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.7"
thiserror = "1.0"
tower = { version = "0.4", features = ["util", "buffer"] }
tower-http = { version = "0.1", features = ["add-extension"] }

[dev-dependencies]
hyper = { version = "0.14", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.6.1", features = ["macros", "rt", "rt-multi-thread"] }
tower = { version = "0.4", features = ["util", "make", "timeout"] }
tracing = "0.1"
tracing-subscriber = "0.2"

[dev-dependencies.tower-http]
version = "0.1"
features = [
    "add-extension",
    "compression",
    "compression-full",
    "fs",
    "trace",
]
